# Generated by Django 4.0.4 on 2022-06-01 17:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=500)),
                ('job_cateagry', models.CharField(choices=[('Human Resource', 'Human Resource'), ('Marketing', 'Marketing'), ('Customer Services', 'Customer Services'), ('Teaching & Education', 'Teaching & Education'), ('Sales & Communication', 'Sales & Communication'), ('Business Development', 'Business Development'), ('others', 'others')], default='', max_length=50)),
                ('job_nature', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Over Time', 'Over Time')], default='', max_length=50)),
                ('job_salary', models.CharField(max_length=50)),
                ('job_vacancy', models.IntegerField()),
                ('job_address', models.CharField(max_length=500)),
                ('job_qualifications', tinymce.models.HTMLField(default='')),
                ('job_description', tinymce.models.HTMLField(default='')),
                ('job_company', tinymce.models.HTMLField(default='')),
            ],
        ),
    ]
