# Generated by Django 4.0.4 on 2022-06-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_logo',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='jobs_logos/'),
        ),
    ]
