# Generated by Django 4.0.4 on 2022-06-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_resume', models.FileField(default=None, max_length=300, null=True, upload_to='user_cv/')),
            ],
        ),
        migrations.AlterField(
            model_name='user_enquiry',
            name='user_email',
            field=models.EmailField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_enquiry',
            name='user_massage',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_enquiry',
            name='user_name',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_enquiry',
            name='user_phone',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
